import Head from 'next/head'
import React, { useState } from 'react'
import * as C from '../styles/Home'
import Clock from '../components/header/clock/Clock'
import { ClockProps } from '../protocols/clock'
import { BiUser } from 'react-icons/bi'
import Link from 'next/link'
import Error from '../components/helpers/Error'

export default function Home() {
  const [input, setInput] = useState<string>('')
  const [password, setPassword] = useState<string>()
  const [error, setError] = useState<string>('')
  const clockProps: ClockProps = {
    language: 'pt-BR',
    dateTimeFormatOptions: {
      day: '2-digit',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit',
    },
  }
  const handlePassword = ({ target }: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(target.value)
    if (!password) {
      setError
    }
  }
  const handleInput = ({ target }: React.ChangeEvent<HTMLInputElement>) => {
    setInput(target.value)
    if (error) {
      setError('')
    } else {
      setError('informe um nome')
    }
  }
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!input) {
      setError('informe um nome')
    }
  }

  return (
    <>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <C.Container>
        <header>
          <Clock
            language={clockProps.language}
            dateTimeFormatOptions={clockProps.dateTimeFormatOptions}
          />
        </header>
        <article className="content-box">
          <div className="content">
            <span>
              <BiUser size={64} />
            </span>
            <form onSubmit={handleSubmit}>
              <input
                type="text"
                placeholder="usuário"
                value={input}
                onChange={handleInput}
              />
              <input
                type="password"
                placeholder="password"
                value={password}
                onChange={handlePassword}
              />
              <Link href="/">criar conta</Link>

              <button>entrar</button>
            </form>{' '}
          </div>
          <Error error={error} />
        </article>
      </C.Container>
    </>
  )
}
