import Head from 'next/head'
import React from 'react'
import Clock from '@/components/header/clock/Clock'
import { ClockProps } from '../protocols/clock'
import { BiUser } from 'react-icons/bi'
import * as C from '../styles/Home'
import { useRouter } from 'next/router'

const clockProps: ClockProps = {
  language: 'pt-BR',
  dateTimeFormatOptions: {
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  },
}

export default function Home() {
  const router = useRouter()

  const handleClick = () => {
    router.push('/desktop')
  }

  return (
    <>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <C.container>
        <header>
          <Clock
            language={clockProps.language}
            dateTimeFormatOptions={clockProps.dateTimeFormatOptions}
          />
        </header>
        <C.contentBox>
          <div className="content">
            <div className="item" onClick={handleClick}>
              <span>
                <BiUser size={40} />
              </span>
              <p>Jefferson</p>
            </div>
          </div>
        </C.contentBox>
      </C.container>
    </>
  )
}
