import Head from 'next/head'
import * as C from '../styles/Home'
import Clock from '../components/header/clock/Clock'
import { ClockProps } from '../protocols/clock'

export default function Home() {
  const clockProps: ClockProps = {
    language: 'pt-BR',
    dateTimeFormatOptions: {
      day: '2-digit',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit',
    },
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <C.Container>
        <header>
          <Clock
            language={clockProps.language}
            dateTimeFormatOptions={clockProps.dateTimeFormatOptions}
          />
        </header>
      </C.Container>
    </>
  )
}
