import Head from 'next/head'
import React from 'react'
import useForm from '../../../hooks/useForm'
import { UserPage } from '../../../components'

interface FieldType {
  type: string
  inputProps: {
    name: string
    placeholder: string
    type: string
  }
}
const createField = (type: string, placeholder: string): FieldType => {
  return {
    type,
    inputProps: {
      name: type,
      placeholder: placeholder,
      type: type,
    },
  }
}

export default function Home() {
  const password = useForm(createField('password', 'senha'))
  const email = useForm(createField('email', 'email'))
  const inputs = [email, password]

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (password.validate() && email.validate()) {
      console.log('campos corretos')
    }
  }

  return (
    <>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserPage
        button="entrar"
        handleSubmit={handleSubmit}
        inputs={inputs}
        linkProps={{ text: 'criar conta', router: '/user/create' }}
      />
    </>
  )
}
